---
- name: restart apache2
  service: name=apache2 state=restarted
  sudo: yes

- name: start apache2
  service: name=apache2 state=started
  sudo: yes

- name: reload apache2
  service: name=apache2 state=reloaded
  sudo: yes

